@startuml payment_sequence_find

actor Client
database "PostgreSQL"

Client -> "nginx": HTTP GET
"nginx" -> "gin-gonic/gin": HTTP GET
"gin-gonic/gin" -> "main.FakeAuthentication": gin.Context
"main.FakeAuthentication" --> "gin-gonic/gin": OrganisationID
"gin-gonic/gin" -> "payment.Handler": Find(...)
"payment.Handler" -> "payment.Resource": Find(...)
"payment.Resource" -> "storage.Payment": Find(...)
"storage.Payment" -> "gorm.io": db.Where(...).First(...)
"gorm.io" -> "PostgreSQL": SQL
"PostgreSQL" --> "gorm.io": ResultSet
"gorm.io" --> "storage.Payment": models.PaymentDB
"storage.Payment" --> "payment.Resource": models.PaymentDB
"payment.Resource" -> "payment.transformFromDB": models.PaymentDB
"payment.transformFromDB" -> "payment.Resource": models.Payment
"payment.Resource" -> "validation": Validate.StructCtx(...)
"validation" --> "payment.Resource": error
"payment.Resource" --> "payment.Handler": models.Payment
"payment.Handler" --> "gin-gonic/gin": models.Payment
"gin-gonic/gin" --> "nginx": HTTP 200 OK
"nginx" --> Client: HTTP 200 OK

participant Client order 10
participant "nginx" order 15
participant "gin-gonic/gin" order 20
participant "main.FakeAuthentication" order 25
participant "payment.Handler" order 30
participant "payment.Resource" order 40
participant "payment.transformFromDB" order 45
participant "validation" order 46
participant "storage.Payment" order 50
participant "gorm.io" order 60
participant "PostgreSQL" order 70
@enduml
